/** Curated Arabic anatomical vocabulary for the BodyParts3D name set.
 *
 * Terms follow the Arabic equivalents of Terminologia Anatomica as taught in
 * Arabic medical curricula (Unified Medical Dictionary / المعجم الطبي الموحد).
 * Nothing here is machine translated: every entry is a deliberate choice, and a
 * name that cannot be built from these entries gets no Arabic term at all so the
 * viewer falls back to the English or Latin name instead of inventing one.
 *
 * NOUNS  token -> {d: definite form, b?: construct (bare) form, g: gender}
 * ADJ    token -> [masculine, feminine]  (definite forms)
 * PHRASES  exact multi-word English -> {d, b?, g}   (matched as a whole name or
 *          as the longest suffix of a segment, so laterality still composes)
 */

/** Grammatical gender drives adjective agreement, so it is recorded per noun. */
export const NOUNS = {
  // Vessels and general vascular vocabulary
  artery: {d: 'الشريان', g: 'm'},
  arteries: {d: 'الشرايين', g: 'f'},
  arteria: {d: 'الشريان', g: 'm'},
  vein: {d: 'الوريد', g: 'm'},
  veins: {d: 'الأوردة', g: 'f'},
  branch: {d: 'الفرع', g: 'm'},
  branches: {d: 'الفروع', g: 'f'},
  trunk: {d: 'الجذع', g: 'm'},
  tributary: {d: 'الرافد', g: 'm'},
  anastomosis: {d: 'المفاغرة', g: 'f'},
  aorta: {d: 'الأبهر', g: 'm'},
  sinus: {d: 'الجيب', g: 'm'},
  plexus: {d: 'الضفيرة', g: 'f'},
  arch: {d: 'القوس', g: 'm'},
  circle: {d: 'الحلقة', g: 'f'},
  network: {d: 'الشبكة', g: 'f'},
  vasculature: {d: 'الأوعية', g: 'f'},
  conduit: {d: 'المجرى', g: 'm'},
  outflow: {d: 'المخرج', g: 'm'},
  inflow: {d: 'المدخل', g: 'm'},

  // Bones and joints
  bone: {d: 'العظم', g: 'm'},
  skeleton: {d: 'الهيكل', g: 'm'},
  vertebra: {d: 'الفقرة', g: 'f'},
  vertebrae: {d: 'الفقرات', g: 'f'},
  rib: {d: 'الضلع', g: 'm'},
  phalanx: {d: 'السلامية', g: 'f'},
  cartilage: {d: 'الغضروف', g: 'm'},
  disk: {d: 'القرص', g: 'm'},
  symphysis: {d: 'الارتفاق', g: 'm'},
  ligament: {d: 'الرباط', g: 'm'},
  tendon: {d: 'الوتر', g: 'm'},
  fascia: {d: 'اللفافة', g: 'f'},
  raphe: {d: 'الرفاء', g: 'm'},
  retinaculum: {d: 'الحاصرة', g: 'f'},
  membrane: {d: 'الغشاء', g: 'm'},
  girdle: {d: 'الحزام', g: 'm'},
  column: {d: 'العمود', g: 'm'},
  cage: {d: 'القفص', g: 'm'},
  process: {d: 'الناتئ', g: 'm'},
  trochlea: {d: 'البكرة', g: 'f'},
  fossa: {d: 'الحفرة', g: 'f'},
  foramen: {d: 'الثقبة', g: 'f'},
  canal: {d: 'القناة', g: 'f'},
  canaliculus: {d: 'القنية', g: 'f'},
  incisure: {d: 'الثلمة', g: 'f'},
  sulcus: {d: 'الأخدود', g: 'm'},
  lamina: {d: 'الصفيحة', g: 'f'},
  plate: {d: 'الصفيحة', g: 'f'},
  skull: {d: 'الجمجمة', g: 'f'},
  basicranium: {d: 'قاعدة الجمجمة', b: 'قاعدة الجمجمة', g: 'f'},
  neurocranium: {d: 'القحف العصبي', b: 'القحف العصبي', g: 'm'},
  viscerocranium: {d: 'القحف الحشوي', b: 'القحف الحشوي', g: 'm'},
  mandible: {d: 'الفك السفلي', b: 'الفك السفلي', g: 'm'},
  maxilla: {d: 'الفك العلوي', b: 'الفك العلوي', g: 'm'},
  vomer: {d: 'الميكعة', g: 'f'},
  ethmoid: {d: 'العظم الغربالي', b: 'العظم الغربالي', g: 'm'},
  sternum: {d: 'القص', g: 'm'},
  manubrium: {d: 'قبضة القص', b: 'قبضة القص', g: 'f'},
  sacrum: {d: 'العجز', g: 'm'},
  atlas: {d: 'الفقرة الأطلسية', b: 'الفقرة الأطلسية', g: 'f'},
  axis: {d: 'الفقرة المحورية', b: 'الفقرة المحورية', g: 'f'},
  femur: {d: 'عظم الفخذ', b: 'عظم الفخذ', g: 'm'},
  humerus: {d: 'عظم العضد', b: 'عظم العضد', g: 'm'},
  clavicle: {d: 'الترقوة', g: 'f'},
  scapula: {d: 'لوح الكتف', b: 'لوح الكتف', g: 'm'},
  radius: {d: 'الكعبرة', g: 'f'},
  ulna: {d: 'الزند', g: 'm'},
  tibia: {d: 'الظنبوب', g: 'm'},
  fibula: {d: 'الشظية', g: 'f'},
  patella: {d: 'الرضفة', g: 'f'},
  calcaneus: {d: 'عظم العقب', b: 'عظم العقب', g: 'm'},
  talus: {d: 'عظم الكاحل', b: 'عظم الكاحل', g: 'm'},
  scaphoid: {d: 'العظم الزورقي', b: 'العظم الزورقي', g: 'm'},
  lunate: {d: 'العظم الهلالي', b: 'العظم الهلالي', g: 'm'},
  triquetral: {d: 'العظم الثلاثي', b: 'العظم الثلاثي', g: 'm'},
  pisiform: {d: 'العظم الحمصي', b: 'العظم الحمصي', g: 'm'},
  trapezium: {d: 'العظم شبه المنحرف', b: 'العظم شبه المنحرف', g: 'm'},
  trapezoid: {d: 'العظم شبه المنحرف الصغير', b: 'العظم شبه المنحرف الصغير', g: 'm'},
  capitate: {d: 'العظم الكبير', b: 'العظم الكبير', g: 'm'},
  hamate: {d: 'العظم الكلابي', b: 'العظم الكلابي', g: 'm'},

  // Regions and body parts
  head: {d: 'الرأس', g: 'm'},
  neck: {d: 'العنق', g: 'm'},
  face: {d: 'الوجه', g: 'm'},
  cheek: {d: 'الخد', g: 'm'},
  jaw: {d: 'الفك', g: 'm'},
  mouth: {d: 'الفم', g: 'm'},
  lip: {d: 'الشفة', g: 'f'},
  tongue: {d: 'اللسان', g: 'm'},
  palate: {d: 'الحنك', g: 'm'},
  uvula: {d: 'اللهاة', g: 'f'},
  gingiva: {d: 'اللثة', g: 'f'},
  tooth: {d: 'السن', g: 'f'},
  chest: {d: 'الصدر', g: 'm'},
  thorax: {d: 'الصدر', g: 'm'},
  abdomen: {d: 'البطن', g: 'm'},
  back: {d: 'الظهر', g: 'm'},
  dorsum: {d: 'الظهر', g: 'm'},
  perineum: {d: 'العجان', g: 'm'},
  pelvis: {d: 'الحوض', g: 'm'},
  hip: {d: 'الورك', g: 'm'},
  thigh: {d: 'الفخذ', g: 'm'},
  knee: {d: 'الركبة', g: 'f'},
  leg: {d: 'الساق', g: 'f'},
  foot: {d: 'القدم', g: 'f'},
  toe: {d: 'إصبع القدم', b: 'إصبع القدم', g: 'm'},
  shoulder: {d: 'الكتف', g: 'm'},
  arm: {d: 'العضد', g: 'm'},
  forearm: {d: 'الساعد', g: 'm'},
  wrist: {d: 'الرسغ', g: 'm'},
  hand: {d: 'اليد', g: 'f'},
  finger: {d: 'الإصبع', g: 'f'},
  thumb: {d: 'الإبهام', g: 'm'},
  limb: {d: 'الطرف', g: 'm'},
  side: {d: 'الجانب', g: 'm'},
  orbit: {d: 'الحجاج', g: 'm'},
  mediastinum: {d: 'المنصف', g: 'm'},
  pubis: {d: 'العانة', g: 'f'},

  // Structural / abstract vocabulary used by the source hierarchy
  part: {d: 'الجزء', g: 'm'},
  parts: {d: 'الأجزاء', g: 'f'},
  portion: {d: 'الجزء', g: 'm'},
  segment: {d: 'القطعة', g: 'f'},
  subdivision: {d: 'القسم', g: 'm'},
  division: {d: 'القسم', g: 'm'},
  sector: {d: 'القطاع', g: 'm'},
  subsector: {d: 'القطاع الفرعي', b: 'القطاع الفرعي', g: 'm'},
  set: {d: 'المجموعة', g: 'f'},
  cluster: {d: 'المجموعة', g: 'f'},
  clusters: {d: 'المجموعات', g: 'f'},
  zone: {d: 'المنطقة', g: 'f'},
  region: {d: 'المنطقة', g: 'f'},
  regions: {d: 'المناطق', g: 'f'},
  compartment: {d: 'الحجيرة', g: 'f'},
  space: {d: 'الحيز', g: 'm'},
  cavity: {d: 'التجويف', g: 'm'},
  chamber: {d: 'الحجرة', g: 'f'},
  wall: {d: 'الجدار', g: 'm'},
  layer: {d: 'الطبقة', g: 'f'},
  leaf: {d: 'الوريقة', g: 'f'},
  leaflet: {d: 'الوريقة', g: 'f'},
  cusp: {d: 'الشرفة', g: 'f'},
  lobe: {d: 'الفص', g: 'm'},
  lobule: {d: 'الفصيص', g: 'm'},
  body: {d: 'الجسم', g: 'm'},
  organ: {d: 'العضو', g: 'm'},
  organs: {d: 'الأعضاء', g: 'f'},
  system: {d: 'الجهاز', g: 'm'},
  apparatus: {d: 'الجهاز', g: 'm'},
  component: {d: 'المكون', g: 'm'},
  content: {d: 'المحتوى', g: 'm'},
  entity: {d: 'الكيان', g: 'm'},
  structure: {d: 'البنية', g: 'f'},
  formation: {d: 'التشكيل', g: 'm'},
  complex: {d: 'المركب', g: 'm'},
  junction: {d: 'الملتقى', g: 'm'},
  continuity: {d: 'الاتصال', g: 'm'},
  boundary: {d: 'الحد', g: 'm'},
  line: {d: 'الخط', g: 'm'},
  root: {d: 'الجذر', g: 'm'},
  ring: {d: 'الحلقة', g: 'f'},
  sac: {d: 'الكيس', g: 'm'},
  lake: {d: 'البحيرة', g: 'f'},
  duct: {d: 'القناة', g: 'f'},
  gland: {d: 'الغدة', g: 'f'},
  tree: {d: 'الشجرة', g: 'f'},
  tract: {d: 'السبيل', g: 'm'},
  cord: {d: 'الحبل', g: 'm'},
  tissue: {d: 'النسيج', g: 'm'},
  matter: {d: 'المادة', g: 'f'},
  parenchyma: {d: 'المتن', g: 'm'},
  cell: {d: 'الخلية', g: 'f'},
  epithelium: {d: 'الظهارة', g: 'f'},
  epidermis: {d: 'البشرة', g: 'f'},
  skin: {d: 'الجلد', g: 'm'},
  integument: {d: 'الغلاف الجلدي', b: 'الغلاف الجلدي', g: 'm'},
  hair: {d: 'الشعر', g: 'm'},
  hairs: {d: 'الشعر', g: 'm'},
  appendage: {d: 'الزائدة', g: 'f'},
  musculature: {d: 'العضلات', g: 'f'},
  muscle: {d: 'العضلة', g: 'f'},
  sphincter: {d: 'العضلة العاصرة', b: 'العضلة العاصرة', g: 'f'},
  curtain: {d: 'الستارة', g: 'f'},
  decussation: {d: 'التصالب', g: 'm'},

  // Heart, chest and circulation
  heart: {d: 'القلب', g: 'm'},
  myocardium: {d: 'عضلة القلب', b: 'عضلة القلب', g: 'f'},
  atrium: {d: 'الأذين', g: 'm'},
  ventricle: {d: 'البطين', g: 'm'},
  valve: {d: 'الصمام', g: 'm'},
  septum: {d: 'الحاجز', g: 'm'},
  diaphragm: {d: 'الحجاب الحاجز', b: 'الحجاب الحاجز', g: 'm'},

  // Respiratory
  nose: {d: 'الأنف', g: 'm'},
  concha: {d: 'القرين', g: 'm'},
  pharynx: {d: 'البلعوم', g: 'm'},
  laryngopharynx: {d: 'البلعوم الحنجري', b: 'البلعوم الحنجري', g: 'm'},
  larynx: {d: 'الحنجرة', g: 'f'},
  epiglottis: {d: 'لسان المزمار', b: 'لسان المزمار', g: 'm'},
  trachea: {d: 'الرغامى', g: 'f'},
  bronchus: {d: 'القصبة', g: 'f'},
  lung: {d: 'الرئة', g: 'f'},

  // Digestive
  esophagus: {d: 'المريء', g: 'm'},
  oesophagus: {d: 'المريء', g: 'm'},
  stomach: {d: 'المعدة', g: 'f'},
  intestine: {d: 'المعي', g: 'm'},
  duodenum: {d: 'الاثني عشر', b: 'الاثني عشر', g: 'm'},
  jejunum: {d: 'الصائم', g: 'm'},
  ileum: {d: 'اللفائفي', g: 'm'},
  cecum: {d: 'الأعور', g: 'm'},
  colon: {d: 'القولون', g: 'm'},
  coli: {d: 'القولون', g: 'm'},
  rectum: {d: 'المستقيم', g: 'm'},
  appendix: {d: 'الزائدة الدودية', b: 'الزائدة الدودية', g: 'f'},
  mesoappendix: {d: 'مساريق الزائدة', b: 'مساريق الزائدة', g: 'm'},
  liver: {d: 'الكبد', g: 'm'},
  hemiliver: {d: 'نصف الكبد', b: 'نصف الكبد', g: 'm'},
  gallbladder: {d: 'المرارة', g: 'f'},
  pancreas: {d: 'البنكرياس', g: 'm'},
  spleen: {d: 'الطحال', g: 'm'},
  peritoneum: {d: 'الصفاق', g: 'm'},
  mesentery: {d: 'المساريقا', g: 'f'},
  mesocolon: {d: 'مساريق القولون', b: 'مساريق القولون', g: 'm'},
  taenia: {d: 'الشريط القولوني', b: 'الشريط القولوني', g: 'm'},

  // Urinary and reproductive
  kidney: {d: 'الكلية', g: 'f'},
  ureter: {d: 'الحالب', g: 'm'},
  bladder: {d: 'المثانة', g: 'f'},
  urethra: {d: 'الإحليل', g: 'm'},
  prostate: {d: 'البروستاتا', g: 'f'},
  testis: {d: 'الخصية', g: 'f'},
  epididymis: {d: 'البربخ', g: 'm'},
  penis: {d: 'القضيب', g: 'm'},
  glans: {d: 'الحشفة', g: 'f'},
  vesicle: {d: 'الحويصلة', g: 'f'},
  mons: {d: 'العانة', g: 'f'},

  // Endocrine and lymphatic
  thymus: {d: 'الغدة الصعترية', b: 'الغدة الصعترية', g: 'f'},

  // Nervous system
  brain: {d: 'الدماغ', g: 'm'},
  brainstem: {d: 'جذع الدماغ', b: 'جذع الدماغ', g: 'm'},
  forebrain: {d: 'الدماغ الأمامي', b: 'الدماغ الأمامي', g: 'm'},
  midbrain: {d: 'الدماغ المتوسط', b: 'الدماغ المتوسط', g: 'm'},
  hindbrain: {d: 'الدماغ الخلفي', b: 'الدماغ الخلفي', g: 'm'},
  telencephalon: {d: 'الدماغ الانتهائي', b: 'الدماغ الانتهائي', g: 'm'},
  diencephalon: {d: 'الدماغ البيني', b: 'الدماغ البيني', g: 'm'},
  metencephalon: {d: 'الدماغ التالي', b: 'الدماغ التالي', g: 'm'},
  cerebellum: {d: 'المخيخ', g: 'm'},
  cerebelli: {d: 'المخيخ', g: 'm'},
  pons: {d: 'الجسر', g: 'm'},
  medulla: {d: 'النخاع', g: 'm'},
  oblongata: {d: 'المستطيل', g: 'm'},
  hemisphere: {d: 'نصف الكرة', b: 'نصف الكرة', g: 'm'},
  cortex: {d: 'القشرة', g: 'f'},
  subcortex: {d: 'تحت القشرة', b: 'تحت القشرة', g: 'f'},
  archicortex: {d: 'القشرة القديمة', b: 'القشرة القديمة', g: 'f'},
  gyrus: {d: 'التلفيف', g: 'm'},
  insula: {d: 'الجزيرة', g: 'f'},
  nucleus: {d: 'النواة', g: 'f'},
  thalamus: {d: 'المهاد', g: 'm'},
  hypothalamus: {d: 'الوطاء', g: 'm'},
  epithalamus: {d: 'فوق المهاد', b: 'فوق المهاد', g: 'm'},
  habenula: {d: 'اللجام', g: 'm'},
  amygdala: {d: 'اللوزة', g: 'f'},
  hippocampus: {d: 'الحصين', g: 'm'},
  putamen: {d: 'البطامة', g: 'f'},
  fornix: {d: 'القبو', g: 'm'},
  commissure: {d: 'الصوار', g: 'm'},
  chiasm: {d: 'التصالب', g: 'm'},
  tectum: {d: 'السقف', g: 'm'},
  peduncle: {d: 'السويقة', g: 'f'},
  colliculus: {d: 'الأكيمة', g: 'f'},
  brachium: {d: 'الذراع الموصلة', b: 'الذراع الموصلة', g: 'f'},
  stria: {d: 'الشريط', g: 'm'},
  aqueduct: {d: 'المسال', g: 'm'},
  ganglion: {d: 'العقدة', g: 'f'},
  nerve: {d: 'العصب', g: 'm'},
  neuraxis: {d: 'المحور العصبي', b: 'المحور العصبي', g: 'm'},
  tentorium: {d: 'الخيمة', g: 'f'},
  mater: {d: 'الأم', g: 'f'},
  capsule: {d: 'المحفظة', g: 'f'},

  // Eye and ear
  eye: {d: 'العين', g: 'f'},
  eyeball: {d: 'مقلة العين', b: 'مقلة العين', g: 'f'},
  eyelid: {d: 'الجفن', g: 'm'},
  eyebrow: {d: 'الحاجب', g: 'm'},
  iris: {d: 'القزحية', g: 'f'},
  cornea: {d: 'القرنية', g: 'f'},
  sclera: {d: 'الصلبة', g: 'f'},
  retina: {d: 'الشبكية', g: 'f'},
  lens: {d: 'العدسة', g: 'f'},
  choroid: {d: 'المشيمية', g: 'f'},
  corona: {d: 'الإكليل', g: 'm'},
  ear: {d: 'الأذن', g: 'f'},
};

/** Definite adjective forms: [masculine, feminine]. */
export const ADJ = {
  right: ['الأيمن', 'اليمنى'],
  left: ['الأيسر', 'اليسرى'],
  anterior: ['الأمامي', 'الأمامية'],
  posterior: ['الخلفي', 'الخلفية'],
  superior: ['العلوي', 'العلوية'],
  inferior: ['السفلي', 'السفلية'],
  upper: ['العلوي', 'العلوية'],
  lower: ['السفلي', 'السفلية'],
  lateral: ['الوحشي', 'الوحشية'],
  medial: ['الإنسي', 'الإنسية'],
  median: ['الناصف', 'الناصفة'],
  middle: ['الأوسط', 'الوسطى'],
  central: ['المركزي', 'المركزية'],
  intermediate: ['المتوسط', 'المتوسطة'],
  terminal: ['الانتهائي', 'الانتهائية'],
  distal: ['القاصي', 'القاصية'],
  proximal: ['الداني', 'الدانية'],
  dorsal: ['الظهري', 'الظهرية'],
  palmar: ['الراحي', 'الراحية'],
  plantar: ['الأخمصي', 'الأخمصية'],
  superficial: ['السطحي', 'السطحية'],
  deep: ['العميق', 'العميقة'],
  internal: ['الباطن', 'الباطنة'],
  external: ['الظاهر', 'الظاهرة'],
  intrinsic: ['الداخلي', 'الداخلية'],
  extrinsic: ['الخارجي', 'الخارجية'],
  innermost: ['الأعمق', 'الأعمق'],
  common: ['المشترك', 'المشتركة'],
  proper: ['الخاص', 'الخاصة'],
  main: ['الرئيسي', 'الرئيسية'],
  accessory: ['الإضافي', 'الإضافية'],
  variant: ['المتغاير', 'المتغايرة'],
  free: ['الحر', 'الحرة'],
  long: ['الطويل', 'الطويلة'],
  short: ['القصير', 'القصيرة'],
  great: ['الكبير', 'الكبيرة'],
  major: ['الكبير', 'الكبيرة'],
  minor: ['الصغير', 'الصغيرة'],
  large: ['الكبير', 'الكبيرة'],
  small: ['الصغير', 'الصغيرة'],
  big: ['الكبير', 'الكبيرة'],
  little: ['الصغير', 'الصغيرة'],
  supreme: ['الأعلى', 'العليا'],
  straight: ['المستقيم', 'المستقيمة'],
  vertical: ['العمودي', 'العمودية'],
  transverse: ['المستعرض', 'المستعرضة'],
  oblique: ['المائل', 'المائلة'],
  ascending: ['الصاعد', 'الصاعدة'],
  descending: ['النازل', 'النازلة'],
  recurrent: ['الراجع', 'الراجعة'],
  perforating: ['النافذ', 'النافذة'],
  communicating: ['الواصل', 'الواصلة'],
  precommunicating: ['قبل الواصل', 'قبل الواصلة'],
  postcommunicating: ['بعد الواصل', 'بعد الواصلة'],
  collateral: ['الجانبي', 'الجانبية'],
  marginal: ['الحافي', 'الحافية'],
  circumflex: ['المنعطف', 'المنعطفة'],
  arcuate: ['المقوس', 'المقوسة'],
  diagonal: ['القطري', 'القطرية'],
  segmental: ['القطعي', 'القطعية'],
  subsegmental: ['تحت القطعي', 'تحت القطعية'],
  lobar: ['الفصي', 'الفصية'],
  lobular: ['الفصيصي', 'الفصيصية'],
  apical: ['القمي', 'القمية'],
  basal: ['القاعدي', 'القاعدية'],
  laterobasal: ['الوحشي القاعدي', 'الوحشية القاعدية'],
  mediobasal: ['الإنسي القاعدي', 'الإنسية القاعدية'],
  apicoposterior: ['القمي الخلفي', 'القمية الخلفية'],
  anterolateral: ['الأمامي الوحشي', 'الأمامية الوحشية'],
  posteromedial: ['الخلفي الإنسي', 'الخلفية الإنسية'],
  inferomedial: ['السفلي الإنسي', 'السفلية الإنسية'],
  'antero-medial': ['الأمامي الإنسي', 'الأمامية الإنسية'],
  subsuperior: ['تحت العلوي', 'تحت العلوية'],
  polar: ['القطبي', 'القطبية'],
  bony: ['العظمي', 'العظمية'],
  osseous: ['العظمي', 'العظمية'],
  cartilaginous: ['الغضروفي', 'الغضروفية'],
  fibrous: ['الليفي', 'الليفية'],
  membranous: ['الغشائي', 'الغشائية'],
  tendinous: ['الوتري', 'الوترية'],
  fascial: ['اللفافي', 'اللفافية'],
  serous: ['المصلي', 'المصلية'],
  mucoid: ['المخاطي', 'المخاطية'],
  loose: ['الرخو', 'الرخوة'],
  solid: ['المصمت', 'المصمتة'],
  hollow: ['المجوف', 'المجوفة'],
  cavitated: ['المجوف', 'المجوفة'],
  soft: ['الرخو', 'الرخوة'],
  flat: ['المسطح', 'المسطحة'],
  irregular: ['غير المنتظم', 'غير المنتظمة'],
  typical: ['النموذجي', 'النموذجية'],
  atypical: ['غير النموذجي', 'غير النموذجية'],
  true: ['الحقيقي', 'الحقيقية'],
  false: ['الكاذب', 'الكاذبة'],
  floating: ['العائم', 'العائمة'],
  pneumatized: ['المهوى', 'المهواة'],
  heterogeneous: ['غير المتجانس', 'غير المتجانسة'],
  material: ['المادي', 'المادية'],
  immaterial: ['غير المادي', 'غير المادية'],
  physical: ['الفيزيائي', 'الفيزيائية'],
  anatomical: ['التشريحي', 'التشريحية'],
  articular: ['المفصلي', 'المفصلية'],
  skeletal: ['الهيكلي', 'الهيكلية'],
  nonskeletal: ['غير الهيكلي', 'غير الهيكلية'],
  musculoskeletal: ['العضلي الهيكلي', 'العضلية الهيكلية'],
  parenchymatous: ['المتني', 'المتنية'],
  nonparenchymatous: ['غير المتني', 'غير المتنية'],
  corticomedullary: ['القشري النخاعي', 'القشرية النخاعية'],
  nuclear: ['النووي', 'النووية'],
  neural: ['العصبي', 'العصبية'],
  nervous: ['العصبي', 'العصبية'],
  autonomic: ['الذاتي', 'الذاتية'],
  parasympathetic: ['نظير الودي', 'نظيرة الودي'],
  connective: ['الضام', 'الضامة'],
  vascular: ['الوعائي', 'الوعائية'],
  arterial: ['الشرياني', 'الشريانية'],
  venous: ['الوريدي', 'الوريدية'],
  systemic: ['الجهازي', 'الجهازية'],
  cardiovascular: ['القلبي الوعائي', 'القلبية الوعائية'],
  cardiac: ['القلبي', 'القلبية'],
  myocardial: ['القلبي العضلي', 'القلبية العضلية'],
  subendocardial: ['تحت الشغافي', 'تحت الشغافية'],
  coronary: ['الإكليلي', 'الإكليلية'],
  mitral: ['التاجي', 'التاجية'],
  tricuspid: ['ثلاثي الشرف', 'ثلاثية الشرف'],
  aortic: ['الأبهري', 'الأبهرية'],
  subaortic: ['تحت الأبهري', 'تحت الأبهرية'],
  pulmonary: ['الرئوي', 'الرئوية'],
  pulmopleural: ['الرئوي الجنبي', 'الرئوية الجنبية'],
  intrapulmonary: ['داخل الرئوي', 'داخل الرئوية'],
  bronchial: ['القصبي', 'القصبية'],
  bronchopulmonary: ['القصبي الرئوي', 'القصبية الرئوية'],
  tracheobronchial: ['الرغامي القصبي', 'الرغامية القصبية'],
  respiratory: ['التنفسي', 'التنفسية'],
  lingular: ['اللساني', 'اللسانية'],
  ventricular: ['البطيني', 'البطينية'],
  interventricular: ['بين البطيني', 'بين البطينية'],
  septal: ['الحاجزي', 'الحاجزية'],
  papillary: ['الحليمي', 'الحليمية'],
  caval: ['الأجوفي', 'الأجوفية'],
  azygos: ['الفردي', 'الفردية'],
  hemiazygos: ['نصف الفردي', 'نصف الفردية'],
  jugular: ['الوداجي', 'الوداجية'],
  carotid: ['السباتي', 'السباتية'],
  subclavian: ['تحت الترقوي', 'تحت الترقوية'],
  brachiocephalic: ['العضدي الرأسي', 'العضدية الرأسية'],
  thyrocervical: ['الدرقي الرقبي', 'الدرقية الرقبية'],
  costocervical: ['الضلعي الرقبي', 'الضلعية الرقبية'],
  vertebral: ['الفقري', 'الفقرية'],
  prevertebral: ['أمام الفقري', 'أمام الفقرية'],
  postvertebral: ['خلف الفقري', 'خلف الفقرية'],
  intervertebral: ['بين الفقري', 'بين الفقرية'],
  suboccipital: ['تحت القذالي', 'تحت القذالية'],
  intracranial: ['داخل القحفي', 'داخل القحفية'],
  cranial: ['القحفي', 'القحفية'],
  basicranial: ['قاعدي القحف', 'قاعدية القحف'],
  cerebral: ['الدماغي', 'الدماغية'],
  cerebellar: ['المخيخي', 'المخيخية'],
  pontine: ['الجسري', 'الجسرية'],
  basilar: ['القاعدي القحفي', 'القاعدية القحفية'],
  thalamic: ['المهادي', 'المهادية'],
  hypothalamic: ['الوطائي', 'الوطائية'],
  thalamoperforating: ['المهادي النافذ', 'المهادية النافذة'],
  thalamogeniculate: ['المهادي الركبي', 'المهادية الركبية'],
  geniculate: ['الركبي', 'الركبية'],
  choroidal: ['المشيمي', 'المشيمية'],
  pericallosal: ['حول الجاسئ', 'حول الجاسئة'],
  callosomarginal: ['الجاسئ الحافي', 'الجاسئة الحافية'],
  splenial: ['الطحالي الجاسئ', 'الطحالية الجاسئة'],
  frontal: ['الجبهي', 'الجبهية'],
  prefrontal: ['أمام الجبهي', 'أمام الجبهية'],
  frontobasal: ['الجبهي القاعدي', 'الجبهية القاعدية'],
  parietal: ['الجداري', 'الجدارية'],
  occipital: ['القذالي', 'القذالية'],
  'temporo-occipital': ['الصدغي القذالي', 'الصدغية القذالية'],
  temporal: ['الصدغي', 'الصدغية'],
  insular: ['الجزيري', 'الجزيرية'],
  angular: ['الزاوي', 'الزاوية'],
  supramarginal: ['فوق الحافي', 'فوق الحافية'],
  precentral: ['أمام المركزي', 'أمام المركزية'],
  postcentral: ['خلف المركزي', 'خلف المركزية'],
  paracentral: ['جانب المركزي', 'جانب المركزية'],
  precuneal: ['أمام الإسفيني', 'أمام الإسفينية'],
  cingulate: ['الحزامي', 'الحزامية'],
  parahippocampal: ['جانب الحصيني', 'جانب الحصينية'],
  hippocampal: ['الحصيني', 'الحصينية'],
  fusiform: ['المغزلي', 'المغزلية'],
  limbic: ['الحوفي', 'الحوفية'],
  caudate: ['المذنب', 'المذنبة'],
  intermediomedial: ['المتوسط الإنسي', 'المتوسطة الإنسية'],
  circumventricular: ['حول البطيني', 'حول البطينية'],
  subarachnoid: ['تحت العنكبوتي', 'تحت العنكبوتية'],
  interpeduncular: ['بين السويقتين', 'بين السويقتين'],
  mammillary: ['الحلمي', 'الحلمية'],
  vermian: ['الدودي', 'الدودية'],
  optic: ['البصري', 'البصرية'],
  ophthalmic: ['العيني', 'العينية'],
  ciliary: ['الهدبي', 'الهدبية'],
  lacrimal: ['الدمعي', 'الدمعية'],
  nasolacrimal: ['الأنفي الدمعي', 'الأنفية الدمعية'],
  'extra-ocular': ['خارج المقلة', 'خارج المقلة'],
  oculomotor: ['المحرك للعين', 'المحركة للعين'],
  trochlear: ['البكري', 'البكرية'],
  supratrochlear: ['فوق البكري', 'فوق البكرية'],
  infratrochlear: ['تحت البكري', 'تحت البكرية'],
  'supra-orbital': ['فوق الحجاجي', 'فوق الحجاجية'],
  orbital: ['الحجاجي', 'الحجاجية'],
  nasociliary: ['الأنفي الهدبي', 'الأنفية الهدبية'],
  trigeminal: ['ثلاثي التوائم', 'ثلاثية التوائم'],
  facial: ['الوجهي', 'الوجهية'],
  auriculotemporal: ['الأذني الصدغي', 'الأذنية الصدغية'],
  vitreous: ['الزجاجي', 'الزجاجية'],
  suspensory: ['المعلق', 'المعلقة'],
  tarsal: ['الرصغي', 'الرصغية'],
  nasal: ['الأنفي', 'الأنفية'],
  alar: ['الجناحي', 'الجناحية'],
  ethmoidal: ['الغربالي', 'الغربالية'],
  sphenoid: ['الوتدي', 'الوتدية'],
  zygomatic: ['الوجني', 'الوجنية'],
  palatine: ['الحنكي', 'الحنكية'],
  faucial: ['البلعومي الحنكي', 'البلعومية الحنكية'],
  mandibular: ['الفكي السفلي', 'الفكية السفلية'],
  maxillary: ['الفكي العلوي', 'الفكية العلوية'],
  submandibular: ['تحت الفك السفلي', 'تحت الفك السفلي'],
  sublingual: ['تحت اللساني', 'تحت اللسانية'],
  salivary: ['اللعابي', 'اللعابية'],
  pharyngeal: ['البلعومي', 'البلعومية'],
  laryngeal: ['الحنجري', 'الحنجرية'],
  cricoid: ['الحلقي', 'الحلقية'],
  arytenoid: ['الطرجهالي', 'الطرجهالية'],
  corniculate: ['القرينوي', 'القرينوية'],
  cuneiform: ['الإسفيني', 'الإسفينية'],
  vocal: ['الصوتي', 'الصوتية'],
  uvular: ['اللهاتي', 'اللهاتية'],
  hyoid: ['اللامي', 'اللامية'],
  infrahyoid: ['تحت اللامي', 'تحت اللامية'],
  suprahyoid: ['فوق اللامي', 'فوق اللامية'],
  'hyo-epiglottic': ['اللامي المزماري', 'اللامية المزمارية'],
  'thyro-epiglottic': ['الدرقي المزماري', 'الدرقية المزمارية'],
  epiglottic: ['المزماري', 'المزمارية'],
  thyroid: ['الدرقي', 'الدرقية'],
  thyrohyoid: ['الدرقي اللامي', 'الدرقية اللامية'],
  cricothyroid: ['الحلقي الدرقي', 'الحلقية الدرقية'],
  pterygomandibular: ['الجناحي الفكي', 'الجناحية الفكية'],
  hepatic: ['الكبدي', 'الكبدية'],
  'pre-hepatic': ['قبل الكبدي', 'قبل الكبدية'],
  intrahepatic: ['داخل الكبدي', 'داخل الكبدية'],
  extrahepatic: ['خارج الكبدي', 'خارج الكبدية'],
  hepatovenous: ['الكبدي الوريدي', 'الكبدية الوريدية'],
  portal: ['البابي', 'البابية'],
  biliary: ['الصفراوي', 'الصفراوية'],
  bile: ['الصفراوي', 'الصفراوية'],
  cystic: ['المراري', 'المرارية'],
  pancreatic: ['البنكرياسي', 'البنكرياسية'],
  pancreaticobiliary: ['البنكرياسي الصفراوي', 'البنكرياسية الصفراوية'],
  pancreaticoduodenal: ['البنكرياسي الاثني عشري', 'البنكرياسية الاثني عشرية'],
  gastroduodenal: ['المعدي الاثني عشري', 'المعدية الاثني عشرية'],
  gastric: ['المعدي', 'المعدية'],
  esophageal: ['المريئي', 'المريئية'],
  oesophageal: ['المريئي', 'المريئية'],
  gastrointestinal: ['المعدي المعوي', 'المعدية المعوية'],
  alimentary: ['الهضمي', 'الهضمية'],
  epiploic: ['الثربي', 'الثربية'],
  'gastro-epiploic': ['المعدي الثربي', 'المعدية الثربية'],
  gastroepiploic: ['المعدي الثربي', 'المعدية الثربية'],
  omentalis: ['الثربي', 'الثربية'],
  mesocolica: ['المساريقي القولوني', 'المساريقية القولونية'],
  libera: ['الحر', 'الحرة'],
  celiac: ['الجوفي', 'الجوفية'],
  coeliac: ['الجوفي', 'الجوفية'],
  mesenteric: ['المساريقي', 'المساريقية'],
  colic: ['القولوني', 'القولونية'],
  ileocolic: ['اللفائفي القولوني', 'اللفائفية القولونية'],
  ileocecal: ['اللفائفي الأعوري', 'اللفائفية الأعورية'],
  ileal: ['اللفائفي', 'اللفائفية'],
  cecal: ['الأعوري', 'الأعورية'],
  sigmoid: ['السيني', 'السينية'],
  rectal: ['المستقيمي', 'المستقيمية'],
  anal: ['الشرجي', 'الشرجية'],
  appendicular: ['الزائدي', 'الزائدية'],
  splenic: ['الطحالي', 'الطحالية'],
  peritoneal: ['الصفاقي', 'الصفاقية'],
  visceral: ['الحشوي', 'الحشوية'],
  renal: ['الكلوي', 'الكلوية'],
  suprarenal: ['الكظري', 'الكظرية'],
  adrenal: ['الكظري', 'الكظرية'],
  ureteric: ['الحالبي', 'الحالبية'],
  urinary: ['البولي', 'البولية'],
  genital: ['التناسلي', 'التناسلية'],
  seminal: ['المنوي', 'المنوية'],
  deferent: ['الناقل', 'الناقلة'],
  testicular: ['الخصوي', 'الخصوية'],
  cavernous: ['الكهفي', 'الكهفية'],
  spongiosum: ['الإسفنجي', 'الإسفنجية'],
  cavernosum: ['الكهفي', 'الكهفية'],
  pudendal: ['الفرجي', 'الفرجية'],
  perineal: ['العجاني', 'العجانية'],
  pelvic: ['الحوضي', 'الحوضية'],
  pubic: ['العاني', 'العانية'],
  iliac: ['الحرقفي', 'الحرقفية'],
  iliolumbar: ['الحرقفي القطني', 'الحرقفية القطنية'],
  iliotibial: ['الحرقفي الظنبوبي', 'الحرقفية الظنبوبية'],
  gluteal: ['الأليوي', 'الأليوية'],
  obturator: ['السدادي', 'السدادية'],
  femoral: ['الفخذي', 'الفخذية'],
  genicular: ['الركبي', 'الركبية'],
  patellar: ['الرضفي', 'الرضفية'],
  popliteal: ['المأبضي', 'المأبضية'],
  saphenous: ['الصافن', 'الصافنة'],
  tibial: ['الظنبوبي', 'الظنبوبية'],
  fibular: ['الشظوي', 'الشظوية'],
  calcaneal: ['العقبي', 'العقبية'],
  pedis: ['القدمي', 'القدمية'],
  dorsalis: ['الظهري', 'الظهرية'],
  metatarsal: ['المشطي القدمي', 'المشطية القدمية'],
  metacarpal: ['المشطي', 'المشطية'],
  carpal: ['الرسغي', 'الرسغية'],
  digital: ['الإصبعي', 'الإصبعية'],
  interosseous: ['بين العظمي', 'بين العظمية'],
  sesamoid: ['السمسمي', 'السمسمية'],
  navicular: ['الزورقي', 'الزورقية'],
  cuboid: ['النردي', 'النردية'],
  radial: ['الكعبري', 'الكعبرية'],
  ulnar: ['الزندي', 'الزندية'],
  brachial: ['العضدي', 'العضدية'],
  humeral: ['العضدي', 'العضدية'],
  antebrachial: ['الساعدي', 'الساعدية'],
  cubital: ['المرفقي', 'المرفقية'],
  basilic: ['الباسليقي', 'الباسليقية'],
  cephalic: ['القيفالي', 'القيفالية'],
  axillary: ['الإبطي', 'الإبطية'],
  subscapular: ['تحت الكتفي', 'تحت الكتفية'],
  suprascapular: ['فوق الكتفي', 'فوق الكتفية'],
  scapular: ['الكتفي', 'الكتفية'],
  thoracodorsal: ['الصدري الظهري', 'الصدرية الظهرية'],
  'thoraco-acromial': ['الصدري الأخرمي', 'الصدرية الأخرمية'],
  acromial: ['الأخرمي', 'الأخرمية'],
  clavicular: ['الترقوي', 'الترقوية'],
  sternal: ['القصي', 'القصية'],
  sternocostal: ['القصي الضلعي', 'القصية الضلعية'],
  costal: ['الضلعي', 'الضلعية'],
  intercostal: ['الوربي', 'الوربية'],
  subcostal: ['تحت الضلعي', 'تحت الضلعية'],
  musculophrenic: ['العضلي الحجابي', 'العضلية الحجابية'],
  phrenic: ['الحجابي', 'الحجابية'],
  epigastric: ['الشرسوفي', 'الشرسوفية'],
  abdominal: ['البطني', 'البطنية'],
  thoracic: ['الصدري', 'الصدرية'],
  cervical: ['الرقبي', 'الرقبية'],
  lumbar: ['القطني', 'القطنية'],
  sacral: ['العجزي', 'العجزية'],
  caudal: ['الذنبي', 'الذنبية'],
  spinal: ['الشوكي', 'الشوكية'],
  axial: ['المحوري', 'المحورية'],
  pectoral: ['الصدري', 'الصدرية'],
  scalene: ['الأخمعي', 'الأخمعية'],
  thenar: ['الإبهامي', 'الإبهامية'],
  hypothenar: ['الخنصري', 'الخنصرية'],
  incisor: ['القاطع', 'القاطعة'],
  canine: ['النابي', 'النابية'],
  premolar: ['الضاحك', 'الضاحكة'],
  molar: ['الرحوي', 'الرحوية'],
  secondary: ['الدائم', 'الدائمة'],
  investing: ['المغلف', 'المغلفة'],
  cardinal: ['الأساسي', 'الأساسية'],
  endocrine: ['الصماوي', 'الصماوية'],
  integumentary: ['الجلدي', 'الجلدية'],
  pituitary: ['النخامي', 'النخامية'],
  pineal: ['الصنوبري', 'الصنوبرية'],
  white: ['الأبيض', 'البيضاء'],
  gray: ['الرمادي', 'الرمادية'],
  human: ['البشري', 'البشرية'],
  index: ['السبابي', 'السبابية'],
  deltoid: ['الدالي', 'الدالية'],
  trapezius: ['شبه المنحرف', 'شبه المنحرفة'],
  quadriceps: ['رباعي الرؤوس', 'رباعية الرؤوس'],
  stylohyoid: ['الإبري اللامي', 'الإبرية اللامية'],
  thyrohyoid_adj: ['الدرقي اللامي', 'الدرقية اللامية'],
};

/** Ordinals, in the masculine and feminine definite forms. */
export const ORDINALS = {
  first: ['الأول', 'الأولى'],
  second: ['الثاني', 'الثانية'],
  third: ['الثالث', 'الثالثة'],
  fourth: ['الرابع', 'الرابعة'],
  fifth: ['الخامس', 'الخامسة'],
  sixth: ['السادس', 'السادسة'],
  seventh: ['السابع', 'السابعة'],
  eighth: ['الثامن', 'الثامنة'],
  ninth: ['التاسع', 'التاسعة'],
  tenth: ['العاشر', 'العاشرة'],
  eleventh: ['الحادي عشر', 'الحادية عشرة'],
  twelfth: ['الثاني عشر', 'الثانية عشرة'],
};

/** Whole English phrases with an established Arabic name. Matched against a full
 * name first, then against the longest suffix of a segment, so laterality and
 * ordinals still compose around them. */
export const PHRASES = {
  // Fingers, toes and their named phalanges
  'index finger': {d: 'السبابة', g: 'f'},
  'middle finger': {d: 'الإصبع الوسطى', b: 'الإصبع الوسطى', g: 'f'},
  'ring finger': {d: 'البنصر', g: 'm'},
  'little finger': {d: 'الخنصر', g: 'm'},
  'big toe': {d: 'إبهام القدم', b: 'إبهام القدم', g: 'm'},
  'little toe': {d: 'خنصر القدم', b: 'خنصر القدم', g: 'm'},
  'hip bone': {d: 'عظم الورك', b: 'عظم الورك', g: 'm'},
  'incisor tooth': {d: 'السن القاطعة', b: 'السن القاطعة', g: 'f'},
  'canine tooth': {d: 'السن النابية', b: 'السن النابية', g: 'f'},
  'premolar tooth': {d: 'السن الضاحكة', b: 'السن الضاحكة', g: 'f'},
  'molar tooth': {d: 'السن الرحوية', b: 'السن الرحوية', g: 'f'},

  // Named landmarks whose Arabic form is fixed
  'vena cava': {d: 'الوريد الأجوف', b: 'الوريد الأجوف', g: 'm'},
  'corpus callosum': {d: 'الجسم الجاسئ', b: 'الجسم الجاسئ', g: 'm'},
  'corpus cavernosum': {d: 'الجسم الكهفي', b: 'الجسم الكهفي', g: 'm'},
  'corpus spongiosum': {d: 'الجسم الإسفنجي', b: 'الجسم الإسفنجي', g: 'm'},
  'globus pallidus': {d: 'الكرة الشاحبة', b: 'الكرة الشاحبة', g: 'f'},
  'medulla oblongata': {d: 'النخاع المستطيل', b: 'النخاع المستطيل', g: 'm'},
  'tuber cinereum': {d: 'الحديبة الرمادية', b: 'الحديبة الرمادية', g: 'f'},
  'lamina terminalis': {d: 'الصفيحة الانتهائية', b: 'الصفيحة الانتهائية', g: 'f'},
  'stria terminalis': {d: 'الشريط الانتهائي', b: 'الشريط الانتهائي', g: 'm'},
  'stria medullaris': {d: 'الشريط النخاعي', b: 'الشريط النخاعي', g: 'm'},
  'tentorium cerebelli': {d: 'خيمة المخيخ', b: 'خيمة المخيخ', g: 'f'},
  'dura mater': {d: 'الأم الجافية', b: 'الأم الجافية', g: 'f'},
  'linea alba': {d: 'الخط الأبيض', b: 'الخط الأبيض', g: 'm'},
  'taenia libera': {d: 'الشريط القولوني الحر', b: 'الشريط القولوني الحر', g: 'm'},
  'taenia omentalis': {d: 'الشريط القولوني الثربي', b: 'الشريط القولوني الثربي', g: 'm'},
  'taenia mesocolica': {d: 'الشريط القولوني المساريقي', b: 'الشريط القولوني المساريقي', g: 'm'},
  'conus elasticus': {d: 'المخروط المرن', b: 'المخروط المرن', g: 'm'},
  'conus artery': {d: 'شريان المخروط', b: 'شريان المخروط', g: 'm'},
  'conus branch': {d: 'فرع المخروط', b: 'فرع المخروط', g: 'm'},
  'xiphoid process': {d: 'الناتئ الرهابي', b: 'الناتئ الرهابي', g: 'm'},
  'optic chiasm': {d: 'التصالب البصري', b: 'التصالب البصري', g: 'm'},
  'cerebral aqueduct': {d: 'المسال الدماغي', b: 'المسال الدماغي', g: 'm'},
  'spinal cord': {d: 'النخاع الشوكي', b: 'النخاع الشوكي', g: 'm'},
  'pituitary gland': {d: 'الغدة النخامية', b: 'الغدة النخامية', g: 'f'},
  'pineal body': {d: 'الجسم الصنوبري', b: 'الجسم الصنوبري', g: 'm'},
  'adrenal gland': {d: 'الغدة الكظرية', b: 'الغدة الكظرية', g: 'f'},
  'thyroid gland': {d: 'الغدة الدرقية', b: 'الغدة الدرقية', g: 'f'},
  'mammillary body': {d: 'الجسم الحلمي', b: 'الجسم الحلمي', g: 'm'},
  'vitreous body': {d: 'الجسم الزجاجي', b: 'الجسم الزجاجي', g: 'm'},
  'geniculate body': {d: 'الجسم الركبي', b: 'الجسم الركبي', g: 'm'},
  'corona ciliaris': {d: 'الإكليل الهدبي', b: 'الإكليل الهدبي', g: 'm'},
  'lacrimal lake': {d: 'البحيرة الدمعية', b: 'البحيرة الدمعية', g: 'f'},
  'lacrimal sac': {d: 'الكيس الدمعي', b: 'الكيس الدمعي', g: 'm'},
  'check ligament': {d: 'الرباط الحاصر', b: 'الرباط الحاصر', g: 'm'},
  'iliotibial tract': {d: 'الشريط الحرقفي الظنبوبي', b: 'الشريط الحرقفي الظنبوبي', g: 'm'},
  'in vivo': {d: 'في الجسم الحي', b: 'في الجسم الحي', g: 'm'},
  '(in-vivo)': {d: 'في الجسم الحي', b: 'في الجسم الحي', g: 'm'},

  // Muscles: the Latin stem carries the name, so each is given outright.
  'abductor hallucis': {d: 'العضلة المبعدة لإبهام القدم', b: 'العضلة المبعدة لإبهام القدم', g: 'f'},
  'abductor pollicis brevis': {d: 'العضلة المبعدة القصيرة للإبهام', b: 'العضلة المبعدة القصيرة للإبهام', g: 'f'},
  'abductor pollicis longus': {d: 'العضلة المبعدة الطويلة للإبهام', b: 'العضلة المبعدة الطويلة للإبهام', g: 'f'},
  'abductor digiti minimi': {d: 'العضلة المبعدة للخنصر', b: 'العضلة المبعدة للخنصر', g: 'f'},
  'adductor brevis': {d: 'العضلة المقربة القصيرة', b: 'العضلة المقربة القصيرة', g: 'f'},
  'adductor longus': {d: 'العضلة المقربة الطويلة', b: 'العضلة المقربة الطويلة', g: 'f'},
  'adductor magnus': {d: 'العضلة المقربة الكبيرة', b: 'العضلة المقربة الكبيرة', g: 'f'},
  'adductor minimus': {d: 'العضلة المقربة الصغرى', b: 'العضلة المقربة الصغرى', g: 'f'},
  'adductor hallucis': {d: 'العضلة المقربة لإبهام القدم', b: 'العضلة المقربة لإبهام القدم', g: 'f'},
  'adductor pollicis': {d: 'العضلة المقربة للإبهام', b: 'العضلة المقربة للإبهام', g: 'f'},
  anconeus: {d: 'العضلة المرفقية', b: 'العضلة المرفقية', g: 'f'},
  aryepiglotticus: {d: 'العضلة الطرجهالية المزمارية', b: 'العضلة الطرجهالية المزمارية', g: 'f'},
  brachialis: {d: 'العضلة العضدية', b: 'العضلة العضدية', g: 'f'},
  brachioradialis: {d: 'العضلة العضدية الكعبرية', b: 'العضلة العضدية الكعبرية', g: 'f'},
  'biceps brachii': {d: 'العضلة ذات الرأسين العضدية', b: 'العضلة ذات الرأسين العضدية', g: 'f'},
  'biceps femoris': {d: 'العضلة ذات الرأسين الفخذية', b: 'العضلة ذات الرأسين الفخذية', g: 'f'},
  'triceps brachii': {d: 'العضلة ثلاثية الرؤوس العضدية', b: 'العضلة ثلاثية الرؤوس العضدية', g: 'f'},
  quadriceps: {d: 'العضلة رباعية الرؤوس', b: 'العضلة رباعية الرؤوس', g: 'f'},
  coccygeus: {d: 'العضلة العصعصية', b: 'العضلة العصعصية', g: 'f'},
  coracobrachialis: {d: 'العضلة الغرابية العضدية', b: 'العضلة الغرابية العضدية', g: 'f'},
  digastric: {d: 'العضلة ذات البطنين', b: 'العضلة ذات البطنين', g: 'f'},
  deltoid: {d: 'العضلة الدالية', b: 'العضلة الدالية', g: 'f'},
  trapezius: {d: 'العضلة شبه المنحرفة', b: 'العضلة شبه المنحرفة', g: 'f'},
  'extensor carpi radialis brevis': {d: 'العضلة الباسطة الكعبرية القصيرة للرسغ', b: 'العضلة الباسطة الكعبرية القصيرة للرسغ', g: 'f'},
  'extensor carpi radialis longus': {d: 'العضلة الباسطة الكعبرية الطويلة للرسغ', b: 'العضلة الباسطة الكعبرية الطويلة للرسغ', g: 'f'},
  'extensor carpi ulnaris': {d: 'العضلة الباسطة الزندية للرسغ', b: 'العضلة الباسطة الزندية للرسغ', g: 'f'},
  'extensor digiti minimi': {d: 'العضلة الباسطة للخنصر', b: 'العضلة الباسطة للخنصر', g: 'f'},
  'extensor digitorum': {d: 'العضلة الباسطة للأصابع', b: 'العضلة الباسطة للأصابع', g: 'f'},
  'extensor digitorum longus': {d: 'العضلة الباسطة الطويلة للأصابع', b: 'العضلة الباسطة الطويلة للأصابع', g: 'f'},
  'extensor hallucis brevis': {d: 'العضلة الباسطة القصيرة لإبهام القدم', b: 'العضلة الباسطة القصيرة لإبهام القدم', g: 'f'},
  'extensor hallucis longus': {d: 'العضلة الباسطة الطويلة لإبهام القدم', b: 'العضلة الباسطة الطويلة لإبهام القدم', g: 'f'},
  'extensor indicis': {d: 'العضلة الباسطة للسبابة', b: 'العضلة الباسطة للسبابة', g: 'f'},
  'extensor pollicis brevis': {d: 'العضلة الباسطة القصيرة للإبهام', b: 'العضلة الباسطة القصيرة للإبهام', g: 'f'},
  'extensor pollicis longus': {d: 'العضلة الباسطة الطويلة للإبهام', b: 'العضلة الباسطة الطويلة للإبهام', g: 'f'},
  'external oblique': {d: 'العضلة المائلة الظاهرة', b: 'العضلة المائلة الظاهرة', g: 'f'},
  'internal oblique': {d: 'العضلة المائلة الباطنة', b: 'العضلة المائلة الباطنة', g: 'f'},
  'flexor accessorius': {d: 'العضلة المثنية الإضافية', b: 'العضلة المثنية الإضافية', g: 'f'},
  'flexor carpi radialis': {d: 'العضلة المثنية الكعبرية للرسغ', b: 'العضلة المثنية الكعبرية للرسغ', g: 'f'},
  'flexor carpi ulnaris': {d: 'العضلة المثنية الزندية للرسغ', b: 'العضلة المثنية الزندية للرسغ', g: 'f'},
  'flexor digiti minimi brevis': {d: 'العضلة المثنية القصيرة للخنصر', b: 'العضلة المثنية القصيرة للخنصر', g: 'f'},
  'flexor digitorum brevis': {d: 'العضلة المثنية القصيرة للأصابع', b: 'العضلة المثنية القصيرة للأصابع', g: 'f'},
  'flexor digitorum longus': {d: 'العضلة المثنية الطويلة للأصابع', b: 'العضلة المثنية الطويلة للأصابع', g: 'f'},
  'flexor digitorum profundus': {d: 'العضلة المثنية العميقة للأصابع', b: 'العضلة المثنية العميقة للأصابع', g: 'f'},
  'flexor digitorum superficialis': {d: 'العضلة المثنية السطحية للأصابع', b: 'العضلة المثنية السطحية للأصابع', g: 'f'},
  'flexor hallucis brevis': {d: 'العضلة المثنية القصيرة لإبهام القدم', b: 'العضلة المثنية القصيرة لإبهام القدم', g: 'f'},
  'flexor hallucis longus': {d: 'العضلة المثنية الطويلة لإبهام القدم', b: 'العضلة المثنية الطويلة لإبهام القدم', g: 'f'},
  'flexor pollicis brevis': {d: 'العضلة المثنية القصيرة للإبهام', b: 'العضلة المثنية القصيرة للإبهام', g: 'f'},
  'flexor pollicis longus': {d: 'العضلة المثنية الطويلة للإبهام', b: 'العضلة المثنية الطويلة للإبهام', g: 'f'},
  'flexor retinaculum': {d: 'حاصرة المثنيات', b: 'حاصرة المثنيات', g: 'f'},
  'gemellus inferior': {d: 'العضلة التوأمية السفلية', b: 'العضلة التوأمية السفلية', g: 'f'},
  'gemellus superior': {d: 'العضلة التوأمية العلوية', b: 'العضلة التوأمية العلوية', g: 'f'},
  genioglossus: {d: 'العضلة الذقنية اللسانية', b: 'العضلة الذقنية اللسانية', g: 'f'},
  geniohyoid: {d: 'العضلة الذقنية اللامية', b: 'العضلة الذقنية اللامية', g: 'f'},
  'gluteus maximus': {d: 'العضلة الأليوية الكبيرة', b: 'العضلة الأليوية الكبيرة', g: 'f'},
  'gluteus medius': {d: 'العضلة الأليوية الوسطى', b: 'العضلة الأليوية الوسطى', g: 'f'},
  'gluteus minimus': {d: 'العضلة الأليوية الصغيرة', b: 'العضلة الأليوية الصغيرة', g: 'f'},
  gracilis: {d: 'العضلة الرشيقة', b: 'العضلة الرشيقة', g: 'f'},
  hyoglossus: {d: 'العضلة اللامية اللسانية', b: 'العضلة اللامية اللسانية', g: 'f'},
  iliacus: {d: 'العضلة الحرقفية', b: 'العضلة الحرقفية', g: 'f'},
  iliococcygeus: {d: 'العضلة الحرقفية العصعصية', b: 'العضلة الحرقفية العصعصية', g: 'f'},
  'iliocostalis cervicis': {d: 'العضلة الحرقفية الضلعية الرقبية', b: 'العضلة الحرقفية الضلعية الرقبية', g: 'f'},
  'iliocostalis lumborum': {d: 'العضلة الحرقفية الضلعية القطنية', b: 'العضلة الحرقفية الضلعية القطنية', g: 'f'},
  'iliocostalis thoracis': {d: 'العضلة الحرقفية الضلعية الصدرية', b: 'العضلة الحرقفية الضلعية الصدرية', g: 'f'},
  'inferior oblique': {d: 'العضلة المائلة السفلية', b: 'العضلة المائلة السفلية', g: 'f'},
  'superior oblique': {d: 'العضلة المائلة العلوية', b: 'العضلة المائلة العلوية', g: 'f'},
  'inferior rectus': {d: 'العضلة المستقيمة السفلية', b: 'العضلة المستقيمة السفلية', g: 'f'},
  'superior rectus': {d: 'العضلة المستقيمة العلوية', b: 'العضلة المستقيمة العلوية', g: 'f'},
  'lateral rectus': {d: 'العضلة المستقيمة الوحشية', b: 'العضلة المستقيمة الوحشية', g: 'f'},
  'medial rectus': {d: 'العضلة المستقيمة الإنسية', b: 'العضلة المستقيمة الإنسية', g: 'f'},
  'rectus femoris': {d: 'العضلة المستقيمة الفخذية', b: 'العضلة المستقيمة الفخذية', g: 'f'},
  'rectus capitis anterior': {d: 'العضلة المستقيمة الأمامية للرأس', b: 'العضلة المستقيمة الأمامية للرأس', g: 'f'},
  'rectus capitis lateralis': {d: 'العضلة المستقيمة الوحشية للرأس', b: 'العضلة المستقيمة الوحشية للرأس', g: 'f'},
  'rectus capitis posterior major': {d: 'العضلة المستقيمة الخلفية الكبيرة للرأس', b: 'العضلة المستقيمة الخلفية الكبيرة للرأس', g: 'f'},
  'rectus capitis posterior minor': {d: 'العضلة المستقيمة الخلفية الصغيرة للرأس', b: 'العضلة المستقيمة الخلفية الصغيرة للرأس', g: 'f'},
  infraspinatus: {d: 'العضلة تحت الشوكية', b: 'العضلة تحت الشوكية', g: 'f'},
  supraspinatus: {d: 'العضلة فوق الشوكية', b: 'العضلة فوق الشوكية', g: 'f'},
  'interspinalis thoracis': {d: 'العضلة بين الشوكية الصدرية', b: 'العضلة بين الشوكية الصدرية', g: 'f'},
  'interspinales cervicis': {d: 'العضلات بين الشوكية الرقبية', b: 'العضلات بين الشوكية الرقبية', g: 'f'},
  'interspinales lumborum': {d: 'العضلات بين الشوكية القطنية', b: 'العضلات بين الشوكية القطنية', g: 'f'},
  intertransversarius: {d: 'العضلة بين النواتئ المستعرضة', b: 'العضلة بين النواتئ المستعرضة', g: 'f'},
  intertransversarii: {d: 'العضلات بين النواتئ المستعرضة', b: 'العضلات بين النواتئ المستعرضة', g: 'f'},
  'crico-arytenoid': {d: 'العضلة الحلقية الطرجهالية', b: 'العضلة الحلقية الطرجهالية', g: 'f'},
  'thyro-arytenoid': {d: 'العضلة الدرقية الطرجهالية', b: 'العضلة الدرقية الطرجهالية', g: 'f'},
  'oblique arytenoid': {d: 'العضلة الطرجهالية المائلة', b: 'العضلة الطرجهالية المائلة', g: 'f'},
  'transverse arytenoid': {d: 'العضلة الطرجهالية المستعرضة', b: 'العضلة الطرجهالية المستعرضة', g: 'f'},
  'levator palpebrae superioris': {d: 'العضلة الرافعة للجفن العلوي', b: 'العضلة الرافعة للجفن العلوي', g: 'f'},
  'levator veli palatini': {d: 'العضلة الرافعة للشراع الحنكي', b: 'العضلة الرافعة للشراع الحنكي', g: 'f'},
  'tensor veli palatini': {d: 'العضلة الموترة للشراع الحنكي', b: 'العضلة الموترة للشراع الحنكي', g: 'f'},
  'tensor fasciae latae': {d: 'العضلة الموترة للفافة العريضة', b: 'العضلة الموترة للفافة العريضة', g: 'f'},
  'levator scapulae': {d: 'العضلة الرافعة للوح الكتف', b: 'العضلة الرافعة للوح الكتف', g: 'f'},
  'levator ani': {d: 'العضلة الرافعة للشرج', b: 'العضلة الرافعة للشرج', g: 'f'},
  'levatores costarum longi': {d: 'العضلات الرافعة الطويلة للأضلاع', b: 'العضلات الرافعة الطويلة للأضلاع', g: 'f'},
  'levatores costarum breves': {d: 'العضلات الرافعة القصيرة للأضلاع', b: 'العضلات الرافعة القصيرة للأضلاع', g: 'f'},
  'longissimus capitis': {d: 'العضلة الطويلة الرأسية', b: 'العضلة الطويلة الرأسية', g: 'f'},
  'longissimus cervicis': {d: 'العضلة الطويلة الرقبية', b: 'العضلة الطويلة الرقبية', g: 'f'},
  'longissimus thoracis': {d: 'العضلة الطويلة الصدرية', b: 'العضلة الطويلة الصدرية', g: 'f'},
  'longus capitis': {d: 'العضلة الطويلة للرأس', b: 'العضلة الطويلة للرأس', g: 'f'},
  'longus colli': {d: 'العضلة الطويلة للعنق', b: 'العضلة الطويلة للعنق', g: 'f'},
  lumbrical: {d: 'العضلة الدودية', b: 'العضلة الدودية', g: 'f'},
  lumbricals: {d: 'العضلات الدودية', b: 'العضلات الدودية', g: 'f'},
  interossei: {d: 'العضلات بين العظمية', b: 'العضلات بين العظمية', g: 'f'},
  mylohyoid: {d: 'العضلة الضرسية اللامية', b: 'العضلة الضرسية اللامية', g: 'f'},
  'obliquus capitis inferior': {d: 'العضلة المائلة السفلية للرأس', b: 'العضلة المائلة السفلية للرأس', g: 'f'},
  'obliquus capitis superior': {d: 'العضلة المائلة العلوية للرأس', b: 'العضلة المائلة العلوية للرأس', g: 'f'},
  'obturator externus': {d: 'العضلة السدادية الظاهرة', b: 'العضلة السدادية الظاهرة', g: 'f'},
  'obturator internus': {d: 'العضلة السدادية الباطنة', b: 'العضلة السدادية الباطنة', g: 'f'},
  omohyoid: {d: 'العضلة الكتفية اللامية', b: 'العضلة الكتفية اللامية', g: 'f'},
  'opponens pollicis': {d: 'العضلة المقابلة للإبهام', b: 'العضلة المقابلة للإبهام', g: 'f'},
  'opponens digiti minimi': {d: 'العضلة المقابلة للخنصر', b: 'العضلة المقابلة للخنصر', g: 'f'},
  'palmaris longus': {d: 'العضلة الراحية الطويلة', b: 'العضلة الراحية الطويلة', g: 'f'},
  palatopharyngeus: {d: 'العضلة الحنكية البلعومية', b: 'العضلة الحنكية البلعومية', g: 'f'},
  salpingopharyngeus: {d: 'العضلة البوقية البلعومية', b: 'العضلة البوقية البلعومية', g: 'f'},
  stylopharyngeus: {d: 'العضلة الإبرية البلعومية', b: 'العضلة الإبرية البلعومية', g: 'f'},
  stylohyoid: {d: 'العضلة الإبرية اللامية', b: 'العضلة الإبرية اللامية', g: 'f'},
  pectineus: {d: 'العضلة المشطية', b: 'العضلة المشطية', g: 'f'},
  'pectoralis major': {d: 'العضلة الصدرية الكبيرة', b: 'العضلة الصدرية الكبيرة', g: 'f'},
  'pectoralis minor': {d: 'العضلة الصدرية الصغيرة', b: 'العضلة الصدرية الصغيرة', g: 'f'},
  piriformis: {d: 'العضلة الكمثرية', b: 'العضلة الكمثرية', g: 'f'},
  plantaris: {d: 'العضلة الأخمصية', b: 'العضلة الأخمصية', g: 'f'},
  platysma: {d: 'العضلة الجلدية للعنق', b: 'العضلة الجلدية للعنق', g: 'f'},
  popliteus: {d: 'العضلة المأبضية', b: 'العضلة المأبضية', g: 'f'},
  'pronator quadratus': {d: 'العضلة الكابة المربعة', b: 'العضلة الكابة المربعة', g: 'f'},
  'pronator teres': {d: 'العضلة الكابة المدورة', b: 'العضلة الكابة المدورة', g: 'f'},
  'psoas major': {d: 'العضلة القطنية الكبيرة', b: 'العضلة القطنية الكبيرة', g: 'f'},
  pubococcygeus: {d: 'العضلة العانية العصعصية', b: 'العضلة العانية العصعصية', g: 'f'},
  puborectalis: {d: 'العضلة العانية المستقيمية', b: 'العضلة العانية المستقيمية', g: 'f'},
  'quadratus femoris': {d: 'العضلة المربعة الفخذية', b: 'العضلة المربعة الفخذية', g: 'f'},
  'rhomboid major': {d: 'العضلة المعينية الكبيرة', b: 'العضلة المعينية الكبيرة', g: 'f'},
  'rhomboid minor': {d: 'العضلة المعينية الصغيرة', b: 'العضلة المعينية الصغيرة', g: 'f'},
  sartorius: {d: 'العضلة الخياطية', b: 'العضلة الخياطية', g: 'f'},
  'scalenus anterior': {d: 'العضلة الأخمعية الأمامية', b: 'العضلة الأخمعية الأمامية', g: 'f'},
  'scalenus medius': {d: 'العضلة الأخمعية الوسطى', b: 'العضلة الأخمعية الوسطى', g: 'f'},
  'scalenus posterior': {d: 'العضلة الأخمعية الخلفية', b: 'العضلة الأخمعية الخلفية', g: 'f'},
  semimembranosus: {d: 'العضلة نصف الغشائية', b: 'العضلة نصف الغشائية', g: 'f'},
  semitendinosus: {d: 'العضلة نصف الوترية', b: 'العضلة نصف الوترية', g: 'f'},
  'semispinalis capitis': {d: 'العضلة نصف الشوكية الرأسية', b: 'العضلة نصف الشوكية الرأسية', g: 'f'},
  'semispinalis cervicis': {d: 'العضلة نصف الشوكية الرقبية', b: 'العضلة نصف الشوكية الرقبية', g: 'f'},
  'semispinalis thoracis': {d: 'العضلة نصف الشوكية الصدرية', b: 'العضلة نصف الشوكية الصدرية', g: 'f'},
  'serratus anterior': {d: 'العضلة المنشارية الأمامية', b: 'العضلة المنشارية الأمامية', g: 'f'},
  'serratus posterior inferior': {d: 'العضلة المنشارية الخلفية السفلية', b: 'العضلة المنشارية الخلفية السفلية', g: 'f'},
  'serratus posterior superior': {d: 'العضلة المنشارية الخلفية العلوية', b: 'العضلة المنشارية الخلفية العلوية', g: 'f'},
  soleus: {d: 'العضلة النعلية', b: 'العضلة النعلية', g: 'f'},
  spinalis: {d: 'العضلة الشوكية', b: 'العضلة الشوكية', g: 'f'},
  'spinalis thoracis': {d: 'العضلة الشوكية الصدرية', b: 'العضلة الشوكية الصدرية', g: 'f'},
  'splenius capitis': {d: 'العضلة الشظوية الرأسية', b: 'العضلة الشظوية الرأسية', g: 'f'},
  'splenius cervicis': {d: 'العضلة الشظوية الرقبية', b: 'العضلة الشظوية الرقبية', g: 'f'},
  sternocleidomastoid: {d: 'العضلة القصية الترقوية الخشائية', b: 'العضلة القصية الترقوية الخشائية', g: 'f'},
  sternohyoid: {d: 'العضلة القصية اللامية', b: 'العضلة القصية اللامية', g: 'f'},
  sternothyroid: {d: 'العضلة القصية الدرقية', b: 'العضلة القصية الدرقية', g: 'f'},
  subclavius: {d: 'العضلة تحت الترقوية', b: 'العضلة تحت الترقوية', g: 'f'},
  subscapularis: {d: 'العضلة تحت الكتفية', b: 'العضلة تحت الكتفية', g: 'f'},
  supinator: {d: 'العضلة الباسطة المستلقية', b: 'العضلة الباسطة المستلقية', g: 'f'},
  'teres major': {d: 'العضلة المدورة الكبيرة', b: 'العضلة المدورة الكبيرة', g: 'f'},
  'teres minor': {d: 'العضلة المدورة الصغيرة', b: 'العضلة المدورة الصغيرة', g: 'f'},
  thyrohyoid: {d: 'العضلة الدرقية اللامية', b: 'العضلة الدرقية اللامية', g: 'f'},
  cricothyroid: {d: 'العضلة الحلقية الدرقية', b: 'العضلة الحلقية الدرقية', g: 'f'},
  'transversus thoracis': {d: 'العضلة المستعرضة الصدرية', b: 'العضلة المستعرضة الصدرية', g: 'f'},
  'vastus intermedius': {d: 'العضلة المتسعة المتوسطة', b: 'العضلة المتسعة المتوسطة', g: 'f'},
  'vastus lateralis': {d: 'العضلة المتسعة الوحشية', b: 'العضلة المتسعة الوحشية', g: 'f'},
  'vastus medialis': {d: 'العضلة المتسعة الإنسية', b: 'العضلة المتسعة الإنسية', g: 'f'},
  vocalis: {d: 'العضلة الصوتية', b: 'العضلة الصوتية', g: 'f'},
  gastrocnemius: {d: 'العضلة التوأمية الساقية', b: 'العضلة التوأمية الساقية', g: 'f'},
  'tibialis anterior': {d: 'العضلة الظنبوبية الأمامية', b: 'العضلة الظنبوبية الأمامية', g: 'f'},
  'tibialis posterior': {d: 'العضلة الظنبوبية الخلفية', b: 'العضلة الظنبوبية الخلفية', g: 'f'},
  'fibularis brevis': {d: 'العضلة الشظوية القصيرة', b: 'العضلة الشظوية القصيرة', g: 'f'},
  'fibularis longus': {d: 'العضلة الشظوية الطويلة', b: 'العضلة الشظوية الطويلة', g: 'f'},
  'fibularis tertius': {d: 'العضلة الشظوية الثالثة', b: 'العضلة الشظوية الثالثة', g: 'f'},
  'pharyngeal constrictor': {d: 'العضلة العاصرة البلعومية', b: 'العضلة العاصرة البلعومية', g: 'f'},
  constrictor: {d: 'العضلة العاصرة', b: 'العضلة العاصرة', g: 'f'},
  rotator: {d: 'العضلة المدورة', b: 'العضلة المدورة', g: 'f'},
  'common tendinous ring': {d: 'الحلقة الوترية المشتركة', b: 'الحلقة الوترية المشتركة', g: 'f'},
  'tendinous arch': {d: 'القوس الوترية', b: 'القوس الوترية', g: 'f'},
  'intermediate tendon': {d: 'الوتر المتوسط', b: 'الوتر المتوسط', g: 'm'},
  'calcaneal tendon': {d: 'وتر العرقوب', b: 'وتر العرقوب', g: 'm'},
  'serratus posterior': {d: 'العضلة المنشارية الخلفية', b: 'العضلة المنشارية الخلفية', g: 'f'},
  'quadriceps femoris': {d: 'العضلة رباعية الرؤوس الفخذية', b: 'العضلة رباعية الرؤوس الفخذية', g: 'f'},
  semispinalis: {d: 'العضلة نصف الشوكية', b: 'العضلة نصف الشوكية', g: 'f'},
  gemellus: {d: 'العضلة التوأمية', b: 'العضلة التوأمية', g: 'f'},
  interspinalis: {d: 'العضلة بين الشوكية', b: 'العضلة بين الشوكية', g: 'f'},
  interspinales: {d: 'العضلات بين الشوكية', b: 'العضلات بين الشوكية', g: 'f'},
  'infraspinatus muscle': {d: 'العضلة تحت الشوكية', b: 'العضلة تحت الشوكية', g: 'f'},
  'interspinalis muscle': {d: 'العضلة بين الشوكية', b: 'العضلة بين الشوكية', g: 'f'},
  'intertransversarius muscle': {d: 'العضلة بين النواتئ المستعرضة', b: 'العضلة بين النواتئ المستعرضة', g: 'f'},
  'rotator muscle': {d: 'العضلة المدورة', b: 'العضلة المدورة', g: 'f'},
  'papillary muscle': {d: 'العضلة الحليمية', b: 'العضلة الحليمية', g: 'f'},
  'uvular muscle': {d: 'العضلة اللهاتية', b: 'العضلة اللهاتية', g: 'f'},
  'anal sphincter': {d: 'العضلة العاصرة الشرجية', b: 'العضلة العاصرة الشرجية', g: 'f'},
  interosseous: {d: 'العضلة بين العظمية', b: 'العضلة بين العظمية', g: 'f'},
  'plantar interosseous': {d: 'العضلة بين العظمية الأخمصية', b: 'العضلة بين العظمية الأخمصية', g: 'f'},
  'dorsal interosseous': {d: 'العضلة بين العظمية الظهرية', b: 'العضلة بين العظمية الظهرية', g: 'f'},
  'palmar interosseous': {d: 'العضلة بين العظمية الراحية', b: 'العضلة بين العظمية الراحية', g: 'f'},
  'dorsal interossei': {d: 'العضلات بين العظمية الظهرية', b: 'العضلات بين العظمية الظهرية', g: 'f'},
  'palmar interossei': {d: 'العضلات بين العظمية الراحية', b: 'العضلات بين العظمية الراحية', g: 'f'},
  'choroid plexus': {d: 'الضفيرة المشيمية', b: 'الضفيرة المشيمية', g: 'f'},
  'lobe branch': {d: 'فرع الفص', b: 'فرع الفص', g: 'm'},
  'lobe tributary': {d: 'رافد الفص', b: 'رافد الفص', g: 'm'},
  'glans penis': {d: 'حشفة القضيب', b: 'حشفة القضيب', g: 'f'},
  'taenia coli': {d: 'الشريط القولوني', b: 'الشريط القولوني', g: 'm'},
  'arteria princeps pollicis': {d: 'الشريان الرئيسي للإبهام', b: 'الشريان الرئيسي للإبهام', g: 'm'},
  'arteria radialis indicis': {d: 'الشريان الكعبري للسبابة', b: 'الشريان الكعبري للسبابة', g: 'm'},
  'hepatovenous segment': {d: 'القطعة الكبدية الوريدية', b: 'القطعة الكبدية الوريدية', g: 'f'},
  'rib cage': {d: 'القفص الصدري', b: 'القفص الصدري', g: 'm'},
  'body wall': {d: 'جدار الجسم', b: 'جدار الجسم', g: 'm'},
  'mons pubis': {d: 'جبل العانة', b: 'جبل العانة', g: 'm'},
  'fascia lata': {d: 'اللفافة العريضة', b: 'اللفافة العريضة', g: 'f'},
  'duct tree': {d: 'شجرة القناة', b: 'شجرة القناة', g: 'f'},
  'outflow part': {d: 'الجزء الخارج', b: 'الجزء الخارج', g: 'm'},
  'inflow part': {d: 'الجزء الداخل', b: 'الجزء الداخل', g: 'm'},
  'constrictor muscle': {d: 'العضلة العاصرة', b: 'العضلة العاصرة', g: 'f'},
  'midbrain tectum': {d: 'سقف الدماغ المتوسط', b: 'سقف الدماغ المتوسط', g: 'm'},
  iliocostalis: {d: 'العضلة الحرقفية الضلعية', b: 'العضلة الحرقفية الضلعية', g: 'f'},
  longissimus: {d: 'العضلة الطويلة', b: 'العضلة الطويلة', g: 'f'},
  splenius: {d: 'العضلة الشظوية', b: 'العضلة الشظوية', g: 'f'},
  'muscle layer': {d: 'الطبقة العضلية', b: 'الطبقة العضلية', g: 'f'},
};

/** Latin (Terminologia Anatomica) forms for the structures students meet by their
 * Latin name. Used for the third line of the detail panel and for search. */
export const LATIN = {
  heart: 'Cor',
  liver: 'Hepar',
  brain: 'Encephalon',
  stomach: 'Gaster',
  spleen: 'Splen',
  pancreas: 'Pancreas',
  'urinary bladder': 'Vesica urinaria',
  trachea: 'Trachea',
  diaphragm: 'Diaphragma',
  esophagus: 'Oesophagus',
  duodenum: 'Duodenum',
  jejunum: 'Jejunum',
  appendix: 'Appendix vermiformis',
  rectum: 'Rectum',
  gallbladder: 'Vesica biliaris',
  tongue: 'Lingua',
  pharynx: 'Pharynx',
  epiglottis: 'Epiglottis',
  cerebellum: 'Cerebellum',
  pons: 'Pons',
  midbrain: 'Mesencephalon',
  'medulla oblongata': 'Medulla oblongata',
  thalamus: 'Thalamus',
  hypothalamus: 'Hypothalamus',
  hippocampus: 'Hippocampus',
  amygdala: 'Corpus amygdaloideum',
  putamen: 'Putamen',
  insula: 'Insula',
  'corpus callosum': 'Corpus callosum',
  'optic chiasm': 'Chiasma opticum',
  sacrum: 'Os sacrum',
  mandible: 'Mandibula',
  maxilla: 'Maxilla',
  sternum: 'Sternum',
  manubrium: 'Manubrium sterni',
  vomer: 'Vomer',
  ethmoid: 'Os ethmoidale',
  atlas: 'Atlas',
  axis: 'Axis',
  prostate: 'Prostata',
  urethra: 'Urethra',
  spleen_alt: 'Lien',
  cecum: 'Caecum',
  thymus: 'Thymus',
  'pituitary gland': 'Hypophysis',
  'pineal body': 'Corpus pineale',
  'thyroid cartilage': 'Cartilago thyroidea',
  'cricoid cartilage': 'Cartilago cricoidea',
  patella: 'Patella',
  femur: 'Os femoris',
  tibia: 'Tibia',
  fibula: 'Fibula',
  humerus: 'Humerus',
  radius: 'Radius',
  ulna: 'Ulna',
  clavicle: 'Clavicula',
  scapula: 'Scapula',
  talus: 'Talus',
  calcaneus: 'Calcaneus',
  iris: 'Iris',
  cornea: 'Cornea',
  sclera: 'Sclera',
  retina: 'Retina',
  lens: 'Lens',
  choroid: 'Choroidea',
};
